### ISSUE TITLE
打开文件显示编译错误

### ISSUE THREAD

**Issue by Moritawa** [hotwords123/yuketang-helper#1]
![{`XR(P}9)VV}YJ~}WF9803Q](https://github.com/hotwords123/yuketang-helper/assets/71846267/786446b1-a5c2-4255-a30d-c0817b2481a3)

**Comment by hotwords123** [comment]
这是一个 Tampermonkey（油猴）脚本，你可能是直接双击打开 JS 文件所以报的这个错，可以上网搜索一下油猴插件和用户脚本的安装教程。
